name: "oneToManyELASTICACHE"
services:
  - name: consumer
    image: docker.io/vhiveease/chained-functions-serving-consumer:elasticache
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "tunable"
      maxScale: "tunable"
    containerConcurrency: 1
  - name: producer
    image: docker.io/vhiveease/chained-functions-serving-producer:elasticache
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "1"
      maxScale: "1"
    containerConcurrency: 1
  - name: driver
    image: docker.io/vhiveease/chained-functions-serving-driver:elasticache
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "1"
      maxScale: "1"
    containerConcurrency: 1
commonEnv:
  - name: TRANSFER_TYPE
    value: "ELASTICACHE"
  - name: ENABLE_TRACING
    value: "false"
  - name: AWS_ACCESS_KEY
    value: ${AWS_ACCESS_KEY}
  - name: AWS_SECRET_KEY
    value: ${AWS_SECRET_KEY}
  - name: AWS_REGION
    value: "us-west-1"
  - name: TRANSFER_SIZE_KB
    value: 10000
  - name: FANIN
    value: "0"
  - name: FANOUT
    value: "0"
tunable:
  name: BROADCAST
  values:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32