apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/minScale: "2"
    spec:
      containerConcurrency: 1
      nodeSelector:
        nodeLabel: B
      containers:
      - env:
        - name: TRANSFER_TYPE
          value: XDT
        - name: ENABLE_TRACING
          value: "false"
        - name: TRACING_ENABLED
          value: "false"
        - name: TRANSFER_SIZE_KB
          value: "10000"
        - name: FANIN
          value: "0"
        - name: FANOUT
          value: "0"
        - name: NO_COPY
          value: "true"
        - name: BROADCAST
          value: "2"
        - name: DST_SERVER_PORT
          value: :80
        image: docker.io/vhiveease/chained-functions-serving-consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: h2c
