name: "oneToOneInline"
services:
  - name: consumer
    image: docker.io/vhiveease/chained-functions-serving-consumer:latest
    ports:
      - name: h2c
        containerPort: 80
    containerConcurrency: 1
  - name: producer
    image: docker.io/vhiveease/chained-functions-serving-producer:latest
    ports:
      - name: h2c
        containerPort: 80
    containerConcurrency: 1
  - name: driver
    image: docker.io/vhiveease/chained-functions-serving-driver:latest
    ports:
      - name: h2c
        containerPort: 80
    containerConcurrency: 1
commonEnv:
  - name: TRANSFER_TYPE
    value: "INLINE"
  - name: ENABLE_TRACING
    value: "true"
tunable:
  name: TRANSFER_SIZE_KB
  values:
    - 10
    - 100
    - 1000
    - 4095