name: "oneToOneInlineNoDriver"
services:
  - name: consumer
    image: docker.io/shyamjesal/chained-functions-serving-consumer:latest
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "1"
      maxScale: "1"
    containerConcurrency: 1
  - name: producer
    image: docker.io/shyamjesal/chained-functions-serving-producer:latest
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "1"
      maxScale: "1"
    containerConcurrency: 1
commonEnv:
  - name: TRANSFER_TYPE
    value: "INLINE"
  - name: ENABLE_TRACING
    value: "false"
tunable:
  name: TRANSFER_SIZE_KB
  values:
    - 10
    - 100
    - 1000
    - 4095