name: "oneToMany"
services:
  - name: consumer
    image: docker.io/vhiveease/chained-functions-serving-consumer:latest
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: tunable
  - name: producer
    image: docker.io/vhiveease/chained-functions-serving-producer:latest
    ports:
      - name: h2c
        containerPort: 80
    containerConcurrency: tunable
commonEnv:
  - name: TRANSFER_TYPE
    value: "S3"
  - name: AWS_ACCESS_KEY
    value: ${AWS_ACCESS_KEY}
  - name: AWS_SECRET_KEY
    value: ${AWS_SECRET_KEY}
  - name: AWS_REGION
    value: "us-west-1"
  - name: ENABLE_TRACING
    value: "true"
tunable:
  name: FAN_AMOUNT
  values:
    - 3
    - 5