name: "oneToOneXDTNoDriver"
services:
  - name: consumer
    image: docker.io/shyamjesal/chained-functions-serving-consumer:latest
    env:
      - name: DST_SERVER_PORT
        value: ":80"
      - name: FANIN
        value: "0"
      - name: FANOUT
        value: "0"
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "1"
      maxScale: "1"
    containerConcurrency: 1
  - name: producer
    image: docker.io/shyamjesal/chained-functions-serving-producer:latest
    ports:
      - name: h2c
        containerPort: 80
    scale:
      minScale: "1"
      maxScale: "1"
    containerConcurrency: 1
commonEnv:
  - name: TRANSFER_TYPE
    value: "XDT"
  - name: ENABLE_TRACING
    value: "false"
  - name: TRACING_ENABLED
    value: "false"

tunable:
  name: TRANSFER_SIZE_KB
  values:
    - 10
    - 100
    - 1000
    - 4095
    - 10000
    - 100000