apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: producer
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
      - env:
        - name: TRANSFER_TYPE
          value: XDT
        - name: ENABLE_TRACING
          value: "false"
        - name: TRACING_ENABLED
          value: "false"
        - name: TRANSFER_SIZE_KB
          value: "10"
        - name: FANIN
          value: "0"
        - name: FANOUT
          value: "0"
        - name: NO_COPY
          value: "true"
        - name: BROADCAST
          value: "8"
        image: docker.io/vhiveease/chained-functions-serving-producer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: h2c
