name: Build and Test OpenYurt Deployer

on:
    push:
      branches: [ openyurt, openyurt-deploy, openyurt-deploy-ci ]
      paths-ignore:
      - 'docs/**'
      - '**.md'
    pull_request:
      branches: [ main, legacy-firecracker-v0.24.0-with-upf-support, openyurt ]
      paths-ignore:
      - 'docs/**'
      - '**.md'
    workflow_dispatch:

env:
    GOOS: linux
    GO111MODULE: on

jobs:
  build_openyurt:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello World"

    - name: Set up Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Check out the code
      uses: actions/checkout@v4

    - name: Build scripts
      run: 
        pushd scripts/openyurt-deployer && go build -o oy_deploy && popd

    - name: Show scripts help info
      run: 
        ./scripts/openyurt-deployer/oy_deploy

